version: "3"

volumes:
  data:
  export:

networks:
  idm_network:

services:
  postgres:
    image: docker.io/postgres:17-alpine
    hostname: postgres-db
    ports:
      - 127.0.0.1:5432:5432  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export 
    networks:
      - idm_network
    restart: unless-stopped
   
